name: Test Plugin

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    if: contains(github.ref, 'tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Check tagged branch
        run: |
          BRANCHS=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHS
          for BRANCH in $BRANCHS ; do
          if [[ "$BRANCH" == "main" ]]; then
           exit 0
          fi
          done
          exit 1

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Plugin
        run: bash bin/build.sh ${{ github.ref }}

      - name: Clean Package
        uses: tarosky/workflows/actions/distignore@main

      - name: Create Zip
        run: zip -r ${{ github.event.repository.name }}.zip ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
