name: Test Plugin

on:
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    name: PHP Syntax Check
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 7.4

  assets:
    name: Stylelint & ESLint
    uses: tarosky/workflows/.github/workflows/npm.yml@main
    with:
        node_version: 20

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [ phpcs, assets ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
